// =============================================================
// before-after template — two shapes side-by-side with an arrow
// between them. The most common pattern in iris's whiteboard:
// "cold → warm", "raw → cooked", "off → on", "before → after".
//
// Slots the model fills:
//   { kind: 'before-after',
//     title: '4-8 word plain-words question title',
//     left:  { shape, color, label, dots? },
//     right: { shape, color, label, dots? },
//     arrow_label: 'heat ↑' }
//
// We never trust the model with coordinates or syntax. Everything
// inside the SVG is generated by these helpers.
// =============================================================

import { COLOR_HEX, COLOR_DEEP, SHAPES, COLORS } from './index.js';

const VIEW_W = 800;
const VIEW_H = 500;
const INK = '#2D2622';
const PAPER = '#FCEFD2';

// Simple deterministic dot palette so dots inside a shape have variety
// but the same template gives the same picture every paint.
const DOT_COLORS = ['#E66363', '#7CB7D0', '#6FB05C', '#FF9B94', '#FFB7A8', '#FFD16B'];

// XML-safe text — labels can include ampersands and angle brackets.
function esc(s) {
  return String(s ?? '')
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

function pickColor(name, fallback = 'yellow') {
  if (typeof name !== 'string') return COLOR_HEX[fallback];
  const k = name.toLowerCase().trim();
  return COLOR_HEX[k] || COLOR_HEX[fallback];
}

function pickShape(name, fallback = 'blob') {
  if (typeof name !== 'string') return fallback;
  const k = name.toLowerCase().trim();
  return SHAPES.includes(k) ? k : fallback;
}

function clampDots(n) {
  const i = Number.isFinite(+n) ? Math.round(+n) : 4;
  return Math.max(0, Math.min(6, i));
}

// ---------- Shape factories ----------
// Each returns a sub-SVG fragment placed at (0,0) in its own local
// frame. The caller wraps it in a <g transform="translate(cx cy)">.
// All shapes are roughly bounded by ±110 wide × ±90 tall so two of
// them fit comfortably on either side of the arrow at x=400.

function shapeWedge(color, deep) {
  return `
    <polygon points="-110,60 110,60 0,-80"
             fill="${color}" stroke="${INK}" stroke-width="4" stroke-linejoin="round"/>
    <line x1="-92" y1="60" x2="-15" y2="-50" stroke="${deep}" stroke-width="2" opacity="0.4"/>
  `;
}

function shapeBlob(color, deep) {
  // wider, melted, irregular — communicates "spread out / loose"
  return `
    <path d="M -105 0 Q -125 35 -85 50 Q -25 60 30 45 Q 90 55 130 38 Q 165 20 125 -12 Q 90 -38 25 -32 Q -45 -38 -90 -16 Z"
          fill="${color}" stroke="${INK}" stroke-width="4" stroke-linejoin="round"/>
  `;
}

function shapeSphere(color, deep) {
  return `
    <circle cx="0" cy="0" r="78" fill="${color}" stroke="${INK}" stroke-width="4"/>
    <ellipse cx="-22" cy="-22" rx="20" ry="14" fill="${deep}" opacity="0.25"/>
  `;
}

function shapeChain(color, deep) {
  // a curving line of beads — protein / polymer / dna feel
  // path the line, then a few circles along it
  return `
    <path d="M -100 30 Q -50 -20 0 0 Q 50 20 100 -25"
          fill="none" stroke="${INK}" stroke-width="3"/>
    <circle cx="-100" cy="30" r="14" fill="${color}" stroke="${INK}" stroke-width="3"/>
    <circle cx="-50"  cy="0"  r="14" fill="${color}" stroke="${INK}" stroke-width="3"/>
    <circle cx="0"    cy="0"  r="14" fill="${deep}"  stroke="${INK}" stroke-width="3"/>
    <circle cx="50"   cy="3"  r="14" fill="${color}" stroke="${INK}" stroke-width="3"/>
    <circle cx="100"  cy="-25" r="14" fill="${color}" stroke="${INK}" stroke-width="3"/>
  `;
}

function shapeRing(color, deep) {
  // thick donut — magnet / fusion / orbit
  return `
    <circle cx="0" cy="0" r="80" fill="${color}" stroke="${INK}" stroke-width="4"/>
    <circle cx="0" cy="0" r="32" fill="${PAPER}" stroke="${INK}" stroke-width="4"/>
    <ellipse cx="0" cy="0" rx="55" ry="14" fill="none" stroke="${deep}" stroke-width="2" opacity="0.45"/>
  `;
}

function shapeBox(color, deep) {
  // rounded rect with a slight 3D-ish corner shading
  return `
    <rect x="-90" y="-65" width="180" height="130" rx="8"
          fill="${color}" stroke="${INK}" stroke-width="4" stroke-linejoin="round"/>
    <line x1="-90" y1="-30" x2="90" y2="-30" stroke="${deep}" stroke-width="2" opacity="0.35"/>
    <line x1="-90" y1="20"  x2="90" y2="20"  stroke="${deep}" stroke-width="2" opacity="0.35"/>
  `;
}

function shapeDrop(color, deep) {
  // teardrop — water, droplet
  return `
    <path d="M 0 -80 Q 60 -20 60 20 Q 60 70 0 70 Q -60 70 -60 20 Q -60 -20 0 -80 Z"
          fill="${color}" stroke="${INK}" stroke-width="4" stroke-linejoin="round"/>
    <ellipse cx="-15" cy="-15" rx="12" ry="20" fill="white" opacity="0.45"/>
  `;
}

function shapeLeaf(color, deep) {
  // leaf-ish — biology, plants
  return `
    <path d="M -90 30 Q -50 -80 60 -50 Q 110 -10 80 50 Q 30 90 -50 70 Q -90 60 -90 30 Z"
          fill="${color}" stroke="${INK}" stroke-width="4" stroke-linejoin="round"/>
    <path d="M -70 30 Q 0 0 70 -30" fill="none" stroke="${deep}" stroke-width="3"/>
  `;
}

const SHAPE_RENDERERS = {
  wedge:  shapeWedge,
  blob:   shapeBlob,
  sphere: shapeSphere,
  chain:  shapeChain,
  ring:   shapeRing,
  box:    shapeBox,
  drop:   shapeDrop,
  leaf:   shapeLeaf,
};

// Place dots inside the shape's bounding box. Even for chain/ring we
// just scatter a few colored circles in a band — they read as "tiny
// pieces inside" without pretending to model the topology.
function dotsInside(count) {
  if (!count) return '';
  // pre-baked positions (deterministic so same template paints same)
  const positions = [
    { x: -55, y: 15 }, { x: -10, y: -5 }, { x:  35, y: 18 },
    { x: -25, y: 35 }, { x:  15, y: 35 }, { x:  60, y: -10 },
  ];
  let out = '';
  for (let i = 0; i < count && i < positions.length; i++) {
    const { x, y } = positions[i];
    const col = DOT_COLORS[i % DOT_COLORS.length];
    out += `<circle cx="${x}" cy="${y}" r="9" fill="${col}" stroke="${INK}" stroke-width="2.5"/>`;
  }
  return out;
}

// Render one side of the picture (left or right). Centered at (cx, cy).
function renderSide(side, cx, cy) {
  const shape = pickShape(side?.shape, 'blob');
  const color = pickColor(side?.color, 'yellow');
  const deep  = COLOR_DEEP[(side?.color || 'yellow').toLowerCase()] || COLOR_DEEP.yellow;
  const label = esc((side?.label || '').slice(0, 80));
  const dots  = clampDots(side?.dots);
  const make  = SHAPE_RENDERERS[shape] || SHAPE_RENDERERS.blob;
  return `
    <g transform="translate(${cx} ${cy})">
      ${make(color, deep)}
      ${dotsInside(dots)}
      <text x="0" y="118" font-family="Caveat, cursive" font-weight="700" font-size="26"
            fill="${INK}" text-anchor="middle">${label}</text>
    </g>
  `;
}

export function renderBeforeAfter(t) {
  const title = esc((t.title || '').slice(0, 80));
  const arrowLabel = esc((t.arrow_label || t.arrowLabel || '').slice(0, 30));

  // arrow + heat label group, centered on x=400
  const arrowSvg = `
    <g transform="translate(340 290)">
      ${arrowLabel ? `
        <text x="60" y="-22" font-family="Caveat, cursive" font-weight="700" font-size="34"
              fill="${COLOR_DEEP.red || '#C84A4A'}" text-anchor="middle"
              transform="rotate(-3 60 -22)">${arrowLabel}</text>
      ` : ''}
      <line x1="0" y1="0" x2="120" y2="0" stroke="${INK}" stroke-width="5"
            marker-end="url(#ba-arrow)"/>
    </g>
  `;

  return `
    <svg viewBox="0 0 ${VIEW_W} ${VIEW_H}" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid meet">
      <defs>
        <marker id="ba-arrow" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="7" markerHeight="7" orient="auto">
          <path d="M 0 0 L 10 5 L 0 10 z" fill="${INK}"/>
        </marker>
      </defs>
      <rect width="${VIEW_W}" height="${VIEW_H}" fill="${PAPER}"/>
      ${title ? `
        <text x="400" y="58" font-family="Caveat, cursive" font-weight="700" font-size="34"
              fill="${INK}" text-anchor="middle" transform="rotate(-1 400 58)">${title}</text>
      ` : ''}
      ${renderSide(t.left, 180, 280)}
      ${arrowSvg}
      ${renderSide(t.right, 610, 290)}
    </svg>
  `.trim();
}
